###################################################
# Location of the input data
###################################################

# Common path among inputs. All inputs do not have to be in the same directory
path: './example_data/'
# Remaining path to each input file.
files: ['example field 2014.shp', 'example field 2016.shp', 'example field 2018.shp']
# names to give each file
file_ids: ['2014', '2016', '2018']
# which field should be used as the border for all fields
grid_field_name: '2018'
# the column name that should be used for clustering in each file
var_of_interest: ['Yld_Vol_Dr', 'Yld_Vol_Dr', 'Yld_V_D']

###################################################
# Find field boundary and clip headlands
###################################################

# Combine header width in in METERS
harvest_width: 4.572
# smoothing parameter for finding field boundary.
# lager numbers (100) are simplier and follow data points less closely
# than smaller numbers (1)
alpha: 50
# number of passes to remove as end rows
passes_to_clip: 3
# number of combine header widths that should be used to create grid cells
cellsize_scaler: 2

###################################################
# Set up simulation experiments
###################################################

# length of simulated plots in METERS
# 300/3.281
plot_length: 91.436
# width of simulated plots in METERS
# 45/3.281
plot_width: 13.715
# width of border betweeen simulated plots in METERS
# 15/3.281
border_width: 4.572
# number of treatments in simulated experiment
treatment_number: 4
# number of blocks in simulated experiment
block_number: 4

###################################################
# Output path
###################################################

# Optional. Path where out figured should be saved
output_path: './example_workflow_plots/'



